chat.achievement.broadcast=&8[&{0}*&8] &{0}&l{1} &7has completed the achievement &{0}&l{2}&7!

achievement.adding_some_flavor.name=Adding Some Flavor
achievement.adding_some_flavor.desc=Beat the green colored rankups

achievement.test.name=Test Achievement
achievement.test.desc=Tee hee