chat.course.not_exist=&8[&c*&8] &7That &ccourse &7does not exist!
chat.achievement.broadcast=&8[&{0}*&8] &{0}&l{1} &7has completed the achievement &{0}&l{2}&7!

achievement.adding_some_flavor.name=Adding Some Flavor
achievement.adding_some_flavor.desc=Beat the green colored rankups

achievement.global_domination.name=Global Domination
achievement.global_domination.desc=Beat all four "World of _" courses

achievement.law_abiding_citizen.name=Law Abiding Citizen
achievement.law_abiding_citizen.desc=Testify in court